# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ftr < Formula
  desc ""
  homepage "https://www.futuralabs.app/"
  version "0.1.40"

  depends_on "zig"
  depends_on "zstd"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/futura-platform/ftr-dist/releases/download/v0.1.40/ftr-dist_0.1.40_darwin_amd64.tar.gz"
      sha256 "5e7e1125a3eb26846c146e9156086dfc99ffcdecde4bc13fab8329c9a2ba81fa"

      def install
        bin.install "ftr"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/futura-platform/ftr-dist/releases/download/v0.1.40/ftr-dist_0.1.40_darwin_arm64.tar.gz"
      sha256 "ca7b861ec36c0f023dbda4d232e55cbecaedc69fe6b5075f70280eb5904ae75d"

      def install
        bin.install "ftr"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/futura-platform/ftr-dist/releases/download/v0.1.40/ftr-dist_0.1.40_linux_amd64.tar.gz"
        sha256 "a485ece94380283d398df3f9bed0844a0cb4f63bd84ac33dfd870cd9ecc0a66c"

        def install
          bin.install "ftr"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/futura-platform/ftr-dist/releases/download/v0.1.40/ftr-dist_0.1.40_linux_arm64.tar.gz"
        sha256 "24c96571862b116e367f4daf47c691b21e09fa0c1cad54771eb391bed3a2ef5e"

        def install
          bin.install "ftr"
        end
      end
    end
  end
end
