# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ftr < Formula
  desc ""
  homepage "https://www.futuralabs.app/"
  version "0.1.54"

  depends_on "zig"
  depends_on "zstd"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/futura-platform/ftr-dist/releases/download/v0.1.54/ftr-dist_0.1.54_darwin_amd64.tar.gz"
      sha256 "e9243bd4937446bfd1e73c61fe96a1698851b9299715efd6c2f4f6baebd08897"

      def install
        bin.install "ftr"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/futura-platform/ftr-dist/releases/download/v0.1.54/ftr-dist_0.1.54_darwin_arm64.tar.gz"
      sha256 "1d2a33a09a001cd36100a8d2b204c71488acc415b86c472abee179b597e32e5b"

      def install
        bin.install "ftr"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/futura-platform/ftr-dist/releases/download/v0.1.54/ftr-dist_0.1.54_linux_amd64.tar.gz"
        sha256 "6df0e0b6e8b6fe52ed6ef28bbfa0c6872ab939c7841f74e2a6188f287679088a"

        def install
          bin.install "ftr"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/futura-platform/ftr-dist/releases/download/v0.1.54/ftr-dist_0.1.54_linux_arm64.tar.gz"
        sha256 "bea82e10a6792c90696c3a9f136123856e4795c18eb51af0c66370657d813aad"

        def install
          bin.install "ftr"
        end
      end
    end
  end
end
