# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class FtrdevreloadDeltaCompression < Formula
  desc ""
  homepage "https://www.futuralabs.app/"
  version "0.0.2"

  depends_on "zig"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/stack1ng/homebrew-stack1ng/releases/download/v0.0.2/homebrew-stack1ng_0.0.2_darwin_amd64.tar.gz"
      sha256 "0df7bd148a8f6622e4096d0981ccec92386139d7db9f88ae5a4f17064add0b5c"

      def install
        bin.install "ftr"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/stack1ng/homebrew-stack1ng/releases/download/v0.0.2/homebrew-stack1ng_0.0.2_darwin_arm64.tar.gz"
      sha256 "792498ea2fcaeb72e3afeb7d22269c7a5527af4b2ecfec6ed2bc0b7f03e94924"

      def install
        bin.install "ftr"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/stack1ng/homebrew-stack1ng/releases/download/v0.0.2/homebrew-stack1ng_0.0.2_linux_amd64.tar.gz"
        sha256 "94e5844fd310963fcf3ae018a290e957a6bdfced71aeeb09aef2afe536090009"

        def install
          bin.install "ftr"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/stack1ng/homebrew-stack1ng/releases/download/v0.0.2/homebrew-stack1ng_0.0.2_linux_arm64.tar.gz"
        sha256 "8ffd17c5efbb64ed5c755d1ced562a2ce9cd5d0840c0c40e01e91d8496a37b1a"

        def install
          bin.install "ftr"
        end
      end
    end
  end
end
