# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ftrdebug < Formula
  desc ""
  homepage "https://www.futuralabs.app/"
  version "0.1.58-debug"

  depends_on "zig"
  depends_on "zstd"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/futura-platform/ftr-dist/releases/download/v0.1.58-debug/ftr-dist_0.1.58-debug_darwin_amd64.tar.gz"
      sha256 "84d5ebc0f1152867809f2e233ffc25bef21ace77514db00efb025b2200d9f045"

      def install
        bin.install "ftr"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/futura-platform/ftr-dist/releases/download/v0.1.58-debug/ftr-dist_0.1.58-debug_darwin_arm64.tar.gz"
      sha256 "84d3d40400f1b2ed246c35b5b99b73531d88fb311bf5fd5cf83a843da784b98b"

      def install
        bin.install "ftr"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/futura-platform/ftr-dist/releases/download/v0.1.58-debug/ftr-dist_0.1.58-debug_linux_amd64.tar.gz"
        sha256 "b87aea895444329345bd16ff2c32cb2a3068534f9bca7ee6b33ad5797fba0cda"

        def install
          bin.install "ftr"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/futura-platform/ftr-dist/releases/download/v0.1.58-debug/ftr-dist_0.1.58-debug_linux_arm64.tar.gz"
        sha256 "5ff9a660ff6def85294d586bb17e758827c06ad58d2d27ea6a55612cfb688ed2"

        def install
          bin.install "ftr"
        end
      end
    end
  end
end
