# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class FtrdecoupleSiteImplementation < Formula
  desc ""
  homepage "https://www.futuralabs.app/"
  version "0.1.12"

  depends_on "zig"
  depends_on :macos

  on_intel do
    url "https://github.com/stack1ng/futura/releases/download/v0.1.12/futura_0.1.12_darwin_amd64.tar.gz"
    sha256 "4fd3e88cbfec3663575dc34e6f92e0e7550392ce1ffa710b72465c360fb07f80"

    def install
      bin.install "ftr"
    end
  end
  on_arm do
    url "https://github.com/stack1ng/futura/releases/download/v0.1.12/futura_0.1.12_darwin_arm64.tar.gz"
    sha256 "01ea6540480ce741a811a691054851b036ba973930d88212537eede8d848b025"

    def install
      bin.install "ftr"
    end
  end
end
