# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class FtrdevreloadDeltaCompression < Formula
  desc ""
  homepage "https://www.futuralabs.app/"
  version "0.0.4"

  depends_on "zig"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/stack1ng/homebrew-stack1ng/releases/download/v0.0.4/homebrew-stack1ng_0.0.4_darwin_amd64.tar.gz"
      sha256 "fbf8046dc0d289cd141070bbe42ec51f5a65572faab2d2e67eb1f3fac45e3456"

      def install
        bin.install "ftr"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/stack1ng/homebrew-stack1ng/releases/download/v0.0.4/homebrew-stack1ng_0.0.4_darwin_arm64.tar.gz"
      sha256 "ef91d9fc4edd1a695440c90c226dce0b239f2860c9302d55f3e848f93095e8b1"

      def install
        bin.install "ftr"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/stack1ng/homebrew-stack1ng/releases/download/v0.0.4/homebrew-stack1ng_0.0.4_linux_amd64.tar.gz"
        sha256 "afb188dfe7eeaf8fb3ad20972ed8e0d4cb7c0f34d60666b1bf52c0f93fafaf70"

        def install
          bin.install "ftr"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/stack1ng/homebrew-stack1ng/releases/download/v0.0.4/homebrew-stack1ng_0.0.4_linux_arm64.tar.gz"
        sha256 "a69b580d12caece4f7fa165f26e229ceb99754aafd6032b4fbefbca984216bee"

        def install
          bin.install "ftr"
        end
      end
    end
  end
end
