# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class FtrdevreloadDeltaCompression < Formula
  desc ""
  homepage "https://www.futuralabs.app/"
  version "0.0.7"

  depends_on "zig"
  depends_on "zstd"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/stack1ng/homebrew-stack1ng/releases/download/v0.0.7/homebrew-stack1ng_0.0.7_darwin_amd64.tar.gz"
      sha256 "571644f12f9254e3819c957df9911466611671cb5dc2b9fc1e4b32295e291c46"

      def install
        bin.install "ftr"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/stack1ng/homebrew-stack1ng/releases/download/v0.0.7/homebrew-stack1ng_0.0.7_darwin_arm64.tar.gz"
      sha256 "2a99ccc03a7310d7540f86c847b525822760b64ffc056e615acaf7695fd764da"

      def install
        bin.install "ftr"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/stack1ng/homebrew-stack1ng/releases/download/v0.0.7/homebrew-stack1ng_0.0.7_linux_amd64.tar.gz"
        sha256 "5dd881f016caf74f0cbe9496ba398b80ca292b63d6c44ed2c5cfc5ecaf71fb53"

        def install
          bin.install "ftr"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/stack1ng/homebrew-stack1ng/releases/download/v0.0.7/homebrew-stack1ng_0.0.7_linux_arm64.tar.gz"
        sha256 "16238fbc552ab790245088a25fe3375203d9f741e1fa767ffdc5627231e758ca"

        def install
          bin.install "ftr"
        end
      end
    end
  end
end
