# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class FtrlambdaRuntime < Formula
  desc ""
  homepage "https://www.futuralabs.app/"
  version "0.0.1-lambda"

  depends_on "zig"
  depends_on "zstd"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/futura-platform/ftr-dist/releases/download/v0.0.1-lambda/ftr-dist_0.0.1-lambda_darwin_amd64.tar.gz"
      sha256 "f9a71f051448a0e2db52a213a97449f75fc2c3d12b506b1e46c0626777264114"

      def install
        bin.install "ftr"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/futura-platform/ftr-dist/releases/download/v0.0.1-lambda/ftr-dist_0.0.1-lambda_darwin_arm64.tar.gz"
      sha256 "cf18cb1d8c4495406018fef9e7790a9367592846b872e51512861bff69863a87"

      def install
        bin.install "ftr"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/futura-platform/ftr-dist/releases/download/v0.0.1-lambda/ftr-dist_0.0.1-lambda_linux_amd64.tar.gz"
      sha256 "3268bbec3aa1d21e8bc692982c4ee4114673ca3904570ad1a2b337918ee20d2e"
      def install
        bin.install "ftr"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/futura-platform/ftr-dist/releases/download/v0.0.1-lambda/ftr-dist_0.0.1-lambda_linux_arm64.tar.gz"
      sha256 "2b8750bbedde1e77c49ebbe3b6ebe8febada5fc85edb6b87d384216d94dd9225"
      def install
        bin.install "ftr"
      end
    end
  end
end
