# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ftrmain < Formula
  desc ""
  homepage "https://www.futuralabs.app/"
  version "0.1.21"

  depends_on "zig"

  on_macos do
    on_intel do
      url "https://github.com/stack1ng/homebrew-stack1ng/releases/download/v0.1.21/homebrew-stack1ng_0.1.21_darwin_amd64.tar.gz"
      sha256 "9b6e222d197bfb1802663b0bcccf8b3487209cbb494c601c8e0234f88fe4d1f9"

      def install
        bin.install "ftr"
      end
    end
    on_arm do
      url "https://github.com/stack1ng/homebrew-stack1ng/releases/download/v0.1.21/homebrew-stack1ng_0.1.21_darwin_arm64.tar.gz"
      sha256 "b7456f8213f87595a468baf85bca715c726b60bfa3e620a85ee5b6148bff746f"

      def install
        bin.install "ftr"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/stack1ng/homebrew-stack1ng/releases/download/v0.1.21/homebrew-stack1ng_0.1.21_linux_amd64.tar.gz"
        sha256 "ec07d0ee495b9482866fff0b5806df6e809d16ca977a24839e11bd6e14498a4a"

        def install
          bin.install "ftr"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/stack1ng/homebrew-stack1ng/releases/download/v0.1.21/homebrew-stack1ng_0.1.21_linux_arm64.tar.gz"
        sha256 "d409885bc0cbfa98ef842a0b4ad27f3455d0a51edb78701d979532f3dd99ca63"

        def install
          bin.install "ftr"
        end
      end
    end
  end
end
